services:
  postgres:
    image: postgres:latest
    container_name: schoolbridge-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: schoolbridge
      TZ: Africa/Kigali
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: schoolbridge-pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: muhirwa.g.oreste@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend

volumes:
  postgres_data:
  pgadmin_data:

networks:
  backend:
